### ISSUE TITLE
在 Facebook 的 Git.tw 社團進行推廣

### ISSUE THREAD

**Issue by taichunmin** [progit/progit2-zh-tw#15]
最近有在 Facebook 的 Git.tw 社團進行推廣，
特此紀錄。

![2015-08-22_232234](https://cloud.githubusercontent.com/assets/2192626/9424612/bf3424c0-4924-11e5-93a3-1ab1f48b93c8.png)

**Comment by YueLinHo** [comment]
我沒有 facebook :sweat_smile:

**Comment by taichunmin** [comment]
@YueLinHo 沒有臉書的還真的是頗稀奇，
我雖然也是比較少在看了，但是還是有在用XD
