### ISSUE TITLE
自動建置已停止更新

### ISSUE THREAD

**Issue by taichunmin** [progit/progit2-zh-tw#28]
我昨天發現 https://progit.org/translations 停止更新了耶
@YueLinHo 你最近的幾個翻譯都沒上去
之前我記得是馬上就會上去了阿
好怪

**Comment by YueLinHo** [comment]
這個我有發現，幾天前上游有人發了相關 issue

**Comment by taichunmin** [comment]
原來是我後知後覺了XD

**Comment by YueLinHo** [comment]
我還沒弄懂 progit2、git-scm、atlas 之前的關係。
不過我猜應該是 atlas 的問題。因為它停止支援了。

**Comment by YueLinHo** [comment]
還好啦! 幾天前的事

**Comment by taichunmin** [comment]
那就靜觀其變XD

**Comment by YueLinHo** [comment]
cf. https://github.com/progit/progit2/issues/810 and https://github.com/progit/progit2/issues/810#issuecomment-339439295

**Comment by taichunmin** [comment]
所以恢復自動部署的意思囉？

**Comment by YueLinHo** [comment]
簡單說，英文版使用 CI 在 master 分支有 tag 時，建立 Release 檔案；至 git scm 網頁的部分，我還沒搞懂(see https://github.com/git/git-scm.com/pull/917)，可能是 progit2 有發行後，過一段時間 git scm 就會過來撿檔案吧!!?

重點好像是各個翻譯版版本庫要自行弄自己的 CI !!!!???
所以暫時先通知你一下有這件事 :D 讓你有心理準備

**Comment by YueLinHo** [comment]
簡單說，英文版使用 CI 在 master 分支有合併 PR 時，自動建 tag 和 Release 檔案；

至於 git scm 網頁的部分，我還沒搞懂，see https://github.com/git/git-scm.com/pull/917 ，可能是 progit2 有發行後，過一段時間 git scm 就會過來撿檔案吧!!?

重點好像是各個翻譯版版本庫要自行弄自己的 CI !!!!???
所以暫時先通知你一下有這件事 :D 讓你有心理準備

**Comment by taichunmin** [comment]
我目前換了新工作以後，公司有在用 GitLab CI，是不用一堆 tag 的說，好怪
我可以單純指定 master 就是要執行的

**Comment by YueLinHo** [comment]
我猜:
GitHub 需要 tag 才能將要發行的檔案放在 Release 頁面中，
然後 git scm 網頁才能來 release 頁面尋找最新的發行檔案。
ben 有試著刪掉 tag，結果發行檔案進到垃圾桶裡了。

或許你可以試試不用 tag 的方式... :P

**Comment by taichunmin** [comment]
正在嘗試中  https://gitlab.com/taichunmin/progit2-zh-tw/

**Comment by taichunmin** [comment]
我已經用 GitLab 來自動建置了
但是格式上好像有非常多的問題
要來找找看該怎麼解決了

https://taichunmin.gitlab.io/progit2-zh-tw/
https://taichunmin.gitlab.io/progit2-zh-tw/progit.pdf
https://taichunmin.gitlab.io/progit2-zh-tw/progit-kf8.epub
https://taichunmin.gitlab.io/progit2-zh-tw/progit.epub

**Comment by taichunmin** [comment]
另外再加上一個中文的解決方案 好像成功解決了版面大亂的問題

**Comment by YueLinHo** [comment]
快速看了一下網頁版和 pdf 版，挺漂亮的!!!!

**Comment by taichunmin** [comment]
在產生的時候還是有很多錯誤
(這是最後一次的記錄 https://gitlab.com/taichunmin/progit2-zh-tw/-/jobs/45531090)
而且我發現最新的 progit2 圖片存放的位置有改
看來需要來找時間更新一下了

**Comment by taichunmin** [comment]
#36
