### ISSUE TITLE
automatic compilation and publishing of PDF and epub 

### ISSUE THREAD

**Issue by jnavila** [progit/progit2-zh-tw#36]
Hi all,

I'm in the process of making an automatic publication of the book on git-scm.com, using asciidoctor and Travis-CI for generating the PDF and epub.

This rework requires to move files around, change how cross-refs are done and change the build scripts. This is quite disruptive and would cause conflicts with ongoing changes.

Please ping me when the repo is idle, so that I can make the transition before you guys restart your work.

Thanks,

Jean-Noël

**Comment by YueLinHo** [comment]
@taichunmin 我覺得可以直接讓 jnavila 進行版本庫的調整事項。至於尚未合併的 PR 我可以之後解完衝突再重發，你覺得如何?

**Comment by taichunmin** [comment]
@YueLinHo 我沒問題，那就辛苦你啦!

**Comment by taichunmin** [comment]
雖然說我還是很好奇怎麽不考慮用 GitLab CI，省掉處理那個莫名奇妙的版本問題XD

**Comment by taichunmin** [comment]
@jnavila Because asciidoc have some issue on generating Chinese pdf, I think you may need my Dockerfile to to that. https://github.com/progit/progit2-zh-tw/blob/master/progit2-docker/Dockerfile

**Comment by taichunmin** [comment]
@jnavila And you can also watch my [`.gitlab-ci.yml`](https://github.com/progit/progit2-zh-tw/blob/master/.gitlab-ci.yml) file.

**Comment by jnavila** [comment]
@taichunmin Thanks for your advices. I already set up the compilation with chloerei's add-ons to asciidoctor. The final setup will follow yours.
